### ISSUE TITLE
Minor issue with `/home/${UNAME}` path in Makefile

### ISSUE THREAD

**Issue by kdh0102** [utcs-scea/KernMLOps#29]
Reporting a minor issue when running KernMLOps on CloudLab machines.

The current Makefile assumes the home path to be `/home/$UNAME`: 
https://github.com/utcs-scea/KernMLOps/blob/b7ba4cc368f9153f2c45632d3bd378bcb4787aa9/Makefile#L58
https://github.com/utcs-scea/KernMLOps/blob/b7ba4cc368f9153f2c45632d3bd378bcb4787aa9/Makefile#L171

But, not all environments have the same home path. (e.g., `/users/$UNAME` in one of my cloudlab machines)

### Suggestion
Replacing `/home/$UNAME` with `$HOME` in the above two lines in the Makefile.
If this fix seems valid, I will proceed with opening a PR.

**Comment by AdityaAtulTewari** [comment]
I think this is valid. Open a PR and I can test it locally before I approve it.
